version: "3.7"

services:
  redis1:
    image: redis:6-alpine
    container_name: redis1
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-network:
        ipv4_address: 10.0.0.11
    expose:
      - 6379
      - 16379
    volumes:
      - $PWD/docker-data/redis:/data
      - $PWD/docker-config/redis1.conf:/usr/local/etc/redis/redis.conf

  redis2:
    image: redis:6-alpine
    container_name: redis2
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-network:
        ipv4_address: 10.0.0.12
    expose:
      - 6379
      - 16379
    volumes:
      - $PWD/docker-data/redis:/data
      - $PWD/docker-config/redis2.conf:/usr/local/etc/redis/redis.conf

  redis3:
    image: redis:6-alpine
    container_name: redis3
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-network:
        ipv4_address: 10.0.0.13
    expose:
      - 6379
      - 16379
    volumes:
      - $PWD/docker-data/redis:/data
      - $PWD/docker-config/redis3.conf:/usr/local/etc/redis/redis.conf

  redis-cluster:
    image: redis:6-alpine
    command: redis-cli --cluster create 10.0.0.11:6379 10.0.0.12:6379 10.0.0.13:6379 --cluster-yes --cluster-replicas 0
    networks:
      - redis-network
    depends_on:
      - redis1
      - redis2
      - redis3

networks:
  redis-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/16
